# Generated by Django 4.2.3 on 2023-07-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('sequence', models.IntegerField()),
                ('sentence', models.CharField(max_length=500)),
                ('drawing', models.BinaryField()),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epyc.game')),
            ],
        ),
    ]
