# Generated by Django 4.2.3 on 2023-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epyc', '0005_rename_gameid_entry_game_id_alter_entry_drawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='drawing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentence',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
