# Generated by Django 4.2.3 on 2023-08-16 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epyc', '0006_alter_entry_drawing_alter_entry_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
