# Generated by Django 4.2.3 on 2023-08-31 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("epyc", "0009_alter_entry_created_at_alter_game_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeUseCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.TextField(unique=True)),
                (
                    "entry_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="epyc.entry"
                    ),
                ),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="epyc.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
