# Generated by Django 4.2.3 on 2023-08-31 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epyc", "0012_rename_entry_id_onetimeusecode_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimeusecode",
            name="expires_in",
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
