name: Backend Deploy
on:
  push:
    paths:
      - '!frontend/**'
      - 'epyc_web/**'
      - 'epyc/**'
      - '.github/workflows/backend-deploy.yml'
    branches:
      - main
jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set Secrets
        run: flyctl secrets set --app "$BACKEND_APP_NAME" FRONT_END_URL="$FRONTEND_URL" ALLOWED_HOSTS="$ALLOWED_HOSTS" CSRF_TRUSTED_ORIGINS="$CSRF_TRUSTED_ORIGINS" SECRET_KEY="$SECRET_KEY"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FRONTEND_URL: 'https://${{ vars.FRONTEND_APP_NAME }}.fly.dev'
          ALLOWED_HOSTS: '[ "${{ vars.BACKEND_APP_NAME }}.fly.dev" ]'
          CSRF_TRUSTED_ORIGINS: '["https://${{ vars.FRONTEND_APP_NAME }}.fly.dev", "https://${{ vars.BACKEND_APP_NAME }}.fly.dev"]'
          BACKEND_APP_NAME: ${{ vars.BACKEND_APP_NAME }}
          FRONTEND_APP_NAME: ${{ vars.FRONTEND_APP_NAME }}
          SECRET_KEY: ${{ secrets.DJANGO_KEY }}
      - name: Deploy via fly
        run: "flyctl deploy --remote-only --app $BACKEND_APP_NAME"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          BACKEND_APP_NAME: ${{ vars.BACKEND_APP_NAME }}
          FRONTEND_APP_NAME: ${{ vars.FRONTEND_APP_NAME }}
