name: Frontend Deploy
on:
  push:
    paths:
      - frontend/**
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - main
jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app $FRONTEND_APP_NAME  --build-secret VITE_BACKEND_HOSTNAME="https://${BACKEND_APP_NAME}.fly.dev"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          BACKEND_APP_NAME: ${{ vars.BACKEND_APP_NAME }}
          FRONTEND_APP_NAME: ${{ vars.FRONTEND_APP_NAME }}


